name: PR Validation

on:
  pull_request:
    branches: [ main, master, dev ]
  push:
    branches: [ main, master, dev ]

jobs:
  validate:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
        
    - name: Update version
      shell: pwsh
      run: ./build.ps1
    
    - name: Build
      run: dotnet build -c Release
      
    - name: Test
      run: dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx"
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: '**/test-results.trx' 